<a href="https://colab.research.google.com/github/VarunMishra1998/Python-/blob/main/bay's_theorem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The Formula:
Bayes' Theorem is expressed as:
P(A|B) = [P(B|A) * P(A)] / P(B)
1.types of bay

In [68]:
import pandas as pd
import numpy as np

In [69]:
df=pd.read_csv("/content/spam.csv")

In [70]:
df.head(10)

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
5     spam  FreeMsg Hey there darling it's been 3 week's n...
6      ham  Even my brother is not like to speak with me. ...
7      ham  As per your request 'Melle Melle (Oru Minnamin...
8     spam  WINNER!! As a valued network customer you have...
9     spam  Had your mobile 11 months or more? U R entitle...

In [71]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [72]:
df['Category']=df["Category"].map({"spam":1,"ham":0})

In [73]:
X=df["Message"]
y=df["Category"]

In [74]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [75]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

In [76]:
clf=Pipeline ([
    ("vector",CountVectorizer()),
     ("model",MultinomialNB())
])

In [77]:
clf.fit(x_train, y_train)

Pipeline(steps=[('vector', CountVectorizer()), ('model', MultinomialNB())])

In [78]:
clf.score(x_test,y_test)

0.9847533632286996

In [79]:
pred=clf.predict(x_test)

In [80]:
from sklearn.metrics import confusion_matrix,classification_report

In [81]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       963
           1       0.98      0.91      0.94       152

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.97      1115
weighted avg       0.98      0.98      0.98      1115

In [82]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

In [83]:
clf.predict(emails)

array([0, 1])

In [84]:
import  pandas as pd
import numpy as np

In [85]:
df1=pd.read_csv("/content/Iris.csv")

In [86]:
df1.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [87]:
  df1["Species"]=df1["Species"].map({"Iris-setosa":0,"Iris-versicolor":1,"Iris-virginica":2})

In [88]:
x=df1.drop(["Species"],axis=1)
y=df1["Species"]

In [94]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [95]:
from sklearn.naive_bayes import GaussianNB

In [96]:
model=GaussianNB()

In [97]:
model.fit(x_train,y_train)

GaussianNB()

In [98]:
model.score(x_test,y_test)

0.9473684210526315

In [99]:
df1

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]